/**
 * How each mentor portrait should be framed inside the square card crop.
 *
 * Generated by running face detection over `public/mentors/*` and solving for
 * the crop that puts the face at 40% of the card height at a consistent size.
 * Safe to hand-edit: `position` is a CSS `object-position`, `origin` is the
 * face's location inside that crop, and `zoom` scales about `origin`. Photos
 * with no entry fall back to {@link defaultMentorPictureFocus}.
 */
export type MentorPictureFocus = {
  position: string;
  origin?: string;
  zoom?: number;
};

export const defaultMentorPictureFocus: MentorPictureFocus = {
  position: "50% 20%",
};

export const mentorPictureFocus: Record<string, MentorPictureFocus> = {
  "mentor-01": { position: "50% 50%", origin: "50% 28%", zoom: 1.34 },
  "mentor-02": { position: "50% 0%" },
  "mentor-03": { position: "50% 0%", origin: "42% 40%", zoom: 1.08 },
  "mentor-04": { position: "50% 50%" },
  "mentor-05": { position: "50% 57%" },
  "mentor-06": { position: "50% 0%", origin: "50% 38%", zoom: 1.14 },
  "mentor-07": { position: "55% 10%", zoom: 1.8 },
  "mentor-08": { position: "68% 50%" },
  "mentor-09": { position: "50% 50%" },
  "mentor-10": { position: "65% 50%", origin: "50% 35%", zoom: 1.75 },
  "mentor-11": { position: "50% 0%" },
  "mentor-12": { position: "50% 0%", origin: "48% 18%", zoom: 1.43 },
  "mentor-13": { position: "50% 0%", origin: "56% 27%", zoom: 1.07 },
  "mentor-14": { position: "50% 0%", origin: "47% 39%", zoom: 1.07 },
  "mentor-15": { position: "50% 0%", origin: "49% 37%", zoom: 1.4 },
  "mentor-16": { position: "50% 0%", origin: "57% 29%", zoom: 1.12 },
  "mentor-17": { position: "50% 0%", origin: "39% 39%", zoom: 1.8 },
  "mentor-18": { position: "72% 50%", origin: "50% 23%", zoom: 1.47 },
  "mentor-19": { position: "50% 42%", origin: "63% 40%", zoom: 1.34 },
  "mentor-20": { position: "50% 10%" },
  "mentor-21": { position: "50% 50%" },
  "mentor-22": { position: "50% 0%" },
  "mentor-23": { position: "50% 0%", origin: "48% 36%", zoom: 1.45 },
  "mentor-24": { position: "50% 5%", origin: "51% 40%", zoom: 1.03 },
  "mentor-25": { position: "44% 50%", origin: "50% 37%", zoom: 1.31 },
  "mentor-26": { position: "52% 50%", origin: "50% 23%", zoom: 1.53 },
  "mentor-27": { position: "50% 42%", origin: "49% 40%", zoom: 1.8 },
  "mentor-28": { position: "50% 50%" },
  "mentor-29": { position: "50% 50%", origin: "46% 26%", zoom: 1.23 },
  "mentor-30": { position: "50% 14%" },
  "mentor-31": { position: "50% 0%" },
  "mentor-32": { position: "100% 50%", origin: "55% 36%", zoom: 1.59 },
  "mentor-33": { position: "50% 46%", origin: "50% 40%", zoom: 1.43 },
  "mentor-34": { position: "50% 8%", origin: "52% 40%", zoom: 1.51 },
  "mentor-35": { position: "50% 0%", origin: "56% 33%", zoom: 1.34 },
  "mentor-36": { position: "100% 50%", origin: "52% 28%", zoom: 1.8 },
  "mentor-37": { position: "50% 13%" },
  "mentor-38": { position: "50% 8%" },
  "mentor-39": { position: "50% 0%", origin: "53% 39%", zoom: 1.76 },
  "mentor-40": { position: "50% 45%", origin: "51% 40%", zoom: 1.11 },
  "mentor-41": { position: "50% 0%" },
  "mentor-42": { position: "50% 0%", origin: "58% 39%", zoom: 1.1 },
  "mentor-43": { position: "50% 50%" },
  "mentor-44": { position: "50% 34%" },
  "mentor-45": { position: "50% 0%" },
  "mentor-46": { position: "50% 0%", origin: "51% 38%", zoom: 1.11 },
  "mentor-47": { position: "47% 50%" },
  "mentor-48": { position: "15% 50%", origin: "50% 25%", zoom: 1.7 },
  "mentor-49": { position: "100% 50%" },
  "mentor-50": { position: "50% 50%" },
  "mentor-51": { position: "0% 50%", origin: "32% 43%", zoom: 1.8 },
  "mentor-52": { position: "50% 50%" },
  "mentor-53": { position: "18% 50%", origin: "50% 36%", zoom: 1.54 },
  "mentor-54": { position: "50% 50%", origin: "47% 33%", zoom: 1.01 },
  "mentor-55": { position: "100% 50%" },
  "mentor-56": { position: "50% 0%", origin: "57% 30%", zoom: 1.61 },
  "mentor-57": { position: "50% 47%", origin: "55% 40%", zoom: 1.8 },
  "mentor-58": { position: "48% 50%", origin: "50% 29%", zoom: 1.5 },
  "mentor-59": { position: "50% 21%" },
  "mentor-60": { position: "92% 50%" },
  "mentor-61": { position: "50% 0%", origin: "53% 21%", zoom: 1.17 },
  "mentor-62": { position: "50% 37%" },
  "mentor-63": { position: "50% 50%" },
  "mentor-64": { position: "50% 0%" },
  "mentor-65": { position: "60% 50%", origin: "50% 23%", zoom: 1.37 },
  "mentor-66": { position: "50% 30%", origin: "45% 40%", zoom: 1.36 },
  "mentor-67": { position: "50% 40%" },
  "mentor-68": { position: "50% 0%" },
  "mentor-69": { position: "50% 2%", origin: "45% 40%", zoom: 1.13 },
  "mentor-70": { position: "50% 0%" },
  "mentor-71": { position: "50% 0%" },
  "mentor-72": { position: "50% 0%", origin: "50% 0%", zoom: 1.2},
  "mentor-73": { position: "50% 0%" },
  "mentor-74": { position: "50% 25%" },
  "mentor-75": { position: "50% 0%", origin: "-10% 0%", zoom: 1.1 },
  "mentor-76": { position: "50% 0%"},
  "mentor-132": { position: "50% 0%", origin: "50% 0%", zoom: 1.2},
  "mentor-133": { position: "50% 0%", origin: "50% 50%", zoom: 1.2},
  "mentor-134": { position: "50% 0%", origin: "50% 0%", zoom: 1.2},
  "mentor-135": { position: "50% 0%", origin: "0% 100%", zoom: 1.2},
};
