/**
 * The program year currently running. Mentors whose `mentorYears` include this
 * number are shown under the "This year's mentors" tab.
 */
export const currentProgramYear = 9;

/**
 * Industry tags a mentor can be filtered by. Kept as a const tuple rather than a
 * TypeScript `enum` so the values stay plain strings once they reach an API.
 */
export const mentorIndustries = [
  "tech-and-innovation",
  "manufacturing",
  "engineering",
  "commercial-and-marketing",
  "entrepreneur-and-start-up",
  "food-and-beverage",
  "financial-and-investment",
] as const;

export type MentorIndustry = (typeof mentorIndustries)[number];

export const mentorIndustryLabels: Record<MentorIndustry, string> = {
  "tech-and-innovation": "Tech & Innovation",
  manufacturing: "Manufacturing",
  engineering: "Engineering",
  "commercial-and-marketing": "Commercial & Marketing",
  "entrepreneur-and-start-up": "Entrepreneur & Start Up",
  "food-and-beverage": "Food & Beverage",
  "financial-and-investment": "Financial & Investment",
};

export type Mentor = {
  id: string;
  /**
   * Portrait shown at the top of the card. Optional — the ChAMP 1-5 roster came
   * from a spreadsheet with no attachments, so those mentors have no photo yet.
   */
  mentorPictureUrl?: string;
  /** Thai nickname, rendered as the card headline (e.g. "พี่เอิร์ธ"). */
  nickname: string;
  fullName: string;
  /**
   * Chula Engineering department abbreviation shown in the pill (e.g. "ICE").
   * Optional — some ChAMP year sheets never recorded a major.
   */
  department?: string;
  /**
   * Intania cohort number, rendered as "Intania {classYear}".
   * Optional — some ChAMP year sheets never recorded it.
   */
  classYear?: number;
  position: string;
  /** Optional — plenty of mentors have no usable logo asset. */
  companyLogoUrl?: string;
  companyName: string;
  industries: MentorIndustry[];
  /** Program years this person mentored in, e.g. [7, 9]. */
  mentorYears: number[];
};

/**
 * Mentor roster sourced from two places:
 * - ChAMP Engineering mentor-intake Airtable base (tables Champ9 / Champ8 /
 *   Champ7 / Champ6) — mentors 01..76.
 * - The "ChAMP Eng mentor" Google Sheet (summary tab listing ChAMP Eng 1..8
 *   TRUE/FALSE membership, plus one tab per program year) — mentors 77..127,
 *   i.e. everyone who only ever mentored in ChAMP 1-5.
 *
 * ChAMP 1-5 caveats (the sheet simply does not carry these columns):
 * - No `mentorPictureUrl` and no `companyLogoUrl` for any of mentors 77..127.
 * - `department` / `classYear` come from whichever year tab recorded them
 *   (ChAMP 1 and ChAMP 3 have Major + Intania; ChAMP 4 and ChAMP 5 have Intania
 *   only; ChAMP 2 has neither). The 12 majors and 2 Intania numbers no tab
 *   recorded were supplied by the ChAMP team and are not traceable to the
 *   sheet — re-deriving this file from the sheet alone would drop them again.
 *   Both fields stay optional so future gaps do not break the card.
 * - `industries` for 77..127 is keyword-inferred from position + company only,
 *   since the ChAMP 1-5 tabs have no industry field at all.
 *
 * Merge rules:
 * - Records are deduplicated by real name (`ชื่อ-นามสกุล` / `ชื่อจริง`), ignoring
 *   title prefixes (ดร./นาย/นาง/นางสาว) and whitespace differences.
 * - When the same person appears in multiple tables, scalar fields (nickname,
 *   fullName, position, companyName, classYear) are taken from the
 *   highest-priority table they appear in:
 *   Champ9 > Champ8 > Champ7 > Champ6 > Champ5 > ... > Champ1.
 *   So the Airtable (Champ6-9) values always win over anything in the sheet,
 *   and nothing in mentors 01..76 was overwritten by ChAMP 1-5 data — only
 *   their `mentorYears` gained the earlier years.
 * - `department` and `industries` are person attributes that do not change
 *   year to year, so they fall back through Champ9 -> Champ8 -> Champ7 ->
 *   Champ6 (Champ7 has neither field in its schema) even when a
 *   lower-priority table is used for the other fields.
 * - `mentorYears` is the union of every table (program year) the person
 *   appears in, not just the priority table.
 * - IDs are stable across re-merges: mentor-01..71 are pinned to the same
 *   people as the original Champ9/Champ7/Champ6 merge (so previously
 *   downloaded photo filenames keep matching); mentor-72..76 are the 5
 *   mentors that only appear in Champ8; mentor-77..127 are the ChAMP 1-5
 *   only mentors, appended in descending `#years` order; mentor-128..136 are
 *   first-time mentors added to the Champ9 table after that first merge, in
 *   the order they showed up there.
 * - `mentorPictureUrl` points at `/mentors/{id}.{ext}` for mentors 01..76 and
 *   is absent for 77..127. The
 *   actual image files are NOT bundled here — Airtable serves attachments via
 *   short-lived signed URLs that this environment's network sandbox can't
 *   reach directly, so run `node scripts/download-mentor-photos.mjs` once
 *   (soon — those signed URLs expire a few hours after being fetched) to pull
 *   every photo into `public/mentors/` at these exact filenames.
 * - `companyLogoUrl` is left unset for every mentor. The Champ9 Airtable table
 *   does carry a Logo attachment for all 35 of its rows, so a logo pass is
 *   possible for the current year — it was skipped here to avoid 35 cards
 *   with logos and 100 without.
 * - `industries` is best-effort, keyword-matched from each table's free-text
 *   industry field (plus role/company as a fallback signal). Treat these as a
 *   useful first pass, not a verified taxonomy — some entries may be missing
 *   a tag or carry an approximate one.
 *
 *   Two conventions cover sectors the taxonomy has no tag for, so keep new
 *   entries consistent with them:
 *   - Management/strategy consulting maps to `commercial-and-marketing`
 *     (mentor-09 TNI, mentor-111 McKinsey, mentor-130 Bain).
 *   - Energy, oil and gas map to `engineering` (mentor-78 Chevron,
 *     mentor-97 Energy Solution, mentor-104 Gulf, mentor-126 PTTEP).
 *
 *   Tags are "company sector, plus what the person actually does", so two
 *   mentors at one company share the sector tags and differ only where their
 *   roles differ. PTTGC is engineering + manufacturing for everyone there,
 *   and mentor-88 adds financial-and-investment for his investment role. Mars
 *   Petcare is manufacturing + food-and-beverage for everyone, and mentor-57
 *   and mentor-106 add engineering for their engineering roles while
 *   mentor-133 (supply chain) does not.
 *
 *   Every mentor should carry at least one tag — an empty `industries` array
 *   hides that person from every industry filter.
 */
export const mentors: Mentor[] = [
  {
    id: "mentor-01",
    mentorPictureUrl: "/mentors/mentor-01.png",
    nickname: "พี่แป๋ว",
    fullName: "ดร. ลิสา พัทธ์วิวัฒน์ศิริ",
    department: "IE",
    classYear: 80,
    position: "Chief Digital Officer",
    companyName: "King Power",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-02",
    mentorPictureUrl: "/mentors/mentor-02.jpeg",
    nickname: "พี่พลอย",
    fullName: "พิชญา โมลเลอร์",
    department: "CHEM",
    classYear: 89,
    position: "Services Business Development Director",
    companyName: "Mastercard",
    industries: ["financial-and-investment"],
    mentorYears: [9],
  },
  {
    id: "mentor-03",
    mentorPictureUrl: "/mentors/mentor-03.jpg",
    nickname: "พี่เต",
    fullName: "เตชนันท์ ตั้งเทวนนท์",
    department: "MET",
    classYear: 86,
    position: "Founder",
    companyName: "Whiteline Group",
    industries: ["commercial-and-marketing", "entrepreneur-and-start-up"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-04",
    mentorPictureUrl: "/mentors/mentor-04.jpg",
    nickname: "พี่เอิร์บ",
    fullName: "ผรณกษม อินทรทัต",
    department: "IE",
    classYear: 86,
    position: "Co-Founder and Managing Director",
    companyName: "Scalyst Co.,Ltd.",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [9],
  },
  {
    id: "mentor-05",
    mentorPictureUrl: "/mentors/mentor-05.jpg",
    nickname: "พี่บิว",
    fullName: "จุฬาพร อิกิติสิริ",
    department: "ME",
    classYear: 87,
    position: "Co-owner, CCO, Digital Strategist",
    companyName: "THINK BIG CONSULTING, THINK BIT, THE BLOW DRY BAR",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-06",
    mentorPictureUrl: "/mentors/mentor-06.jpg",
    nickname: "พี่เหลียง",
    fullName: "ธนศักย์ เฉลิมกิตติชัย",
    department: "IE",
    classYear: 92,
    position: "Co-Founder",
    companyName: "บริษัท 425 ดีกรี จำกัด",
    industries: ["commercial-and-marketing", "entrepreneur-and-start-up"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-07",
    mentorPictureUrl: "/mentors/mentor-07.jpeg",
    nickname: "พี่ตั๋ง",
    fullName: "พรเทพ ชูพันธุ์",
    department: "EE",
    classYear: 79,
    position: "Corporate Strategy and Investment",
    companyName: "Gulf Development Public Company Limited",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-08",
    mentorPictureUrl: "/mentors/mentor-08.jpg",
    nickname: "พี่วาเลนไทน์",
    fullName: "อภิรดี จิตเปี่ยมวิริยะ",
    department: "PETRO",
    classYear: 91,
    position: "Digital Platform Manager",
    companyName: "SCG Cement",
    industries: ["tech-and-innovation", "manufacturing"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-09",
    mentorPictureUrl: "/mentors/mentor-09.jpeg",
    nickname: "พี่เอก",
    fullName: "ธนัย ชรินทร์สาร",
    department: "CIVIL",
    classYear: 74,
    position: "Strategy Professional",
    companyName: "TNI and Associates",
    industries: ["commercial-and-marketing"],
    mentorYears: [9],
  },
  {
    id: "mentor-10",
    mentorPictureUrl: "/mentors/mentor-10.jpg",
    nickname: "พี่มิก",
    fullName: "กฤษดา กฤตยากีรณ",
    department: "AE",
    classYear: 81,
    position: "CEO & Co-founder",
    companyName: "MuvMi (Urban Mobility Tech Co. Ltd.)",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [4, 9],
  },
  {
    id: "mentor-11",
    mentorPictureUrl: "/mentors/mentor-11.jpg",
    nickname: "พี่เฉิน",
    fullName: "รณัฐชัย เฉินบำรุง",
    department: "CP",
    classYear: 93,
    position: "Co-Founder",
    companyName: "Cleverse",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-12",
    mentorPictureUrl: "/mentors/mentor-12.jpg",
    nickname: "พี่หญิง",
    fullName: "เอกาญ ปัญญาคำเลิศ",
    department: "IE",
    classYear: 82,
    position: "Chief Executive Officer",
    companyName: "InnovestX Securities Co., Ltd.",
    industries: ["financial-and-investment"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-13",
    mentorPictureUrl: "/mentors/mentor-13.jpg",
    nickname: "พี่วีร์",
    fullName: "วีร์ สิรสุนทร",
    department: "CHEM",
    classYear: 83,
    position: "Cofounder and CEO",
    companyName: "Primo World Co., Ltd.",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-14",
    mentorPictureUrl: "/mentors/mentor-14.jpg",
    nickname: "พี่ก๊วยเจ๋ง",
    fullName: "รับชัย ชินสุวรรณ",
    department: "IE",
    classYear: 87,
    position: "MD",
    companyName: "Skooldio",
    industries: ["tech-and-innovation", "manufacturing", "commercial-and-marketing", "entrepreneur-and-start-up", "food-and-beverage"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-15",
    mentorPictureUrl: "/mentors/mentor-15.jpg",
    nickname: "พี่กู๊ด",
    fullName: "ศิรพันธ์ ยงวัฒนานันท์",
    department: "IE",
    classYear: 87,
    position: "เลขานุการของเลขาธิการคณะกรรมการส่งเสริมการลงทุน",
    companyName: "สำนักงานคณะกรรมการส่งเสริมการลงทุน (BOI)",
    industries: ["financial-and-investment"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-16",
    mentorPictureUrl: "/mentors/mentor-16.jpg",
    nickname: "พี่แบงค์",
    fullName: "สิทธินันท์ พลวิสุทธิ์ศักดิ์",
    department: "IE",
    classYear: 90,
    position: "CEO",
    companyName: "Content Shifu Co., Ltd.",
    industries: ["commercial-and-marketing"],
    mentorYears: [9],
  },
  {
    id: "mentor-17",
    mentorPictureUrl: "/mentors/mentor-17.jpg",
    nickname: "พี่หนูลี",
    fullName: "สุชารีย์ รวิธรธาดา",
    department: "CIVIL",
    classYear: 93,
    position: "MD, Founder",
    companyName: "บริษัท ไฟว์วันวัน ครีเอชั่น จำกัด, บริษัท ไฟว์วันวัน ทรานส์ โซลูชั่น จำกัด",
    industries: ["engineering", "entrepreneur-and-start-up"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-18",
    mentorPictureUrl: "/mentors/mentor-18.jpg",
    nickname: "พี่แจ๊ค",
    fullName: "ชวิน ศุภวงศ์",
    department: "ME",
    classYear: 87,
    position: "Head of Innovation",
    companyName: "Learn Corporation",
    industries: ["tech-and-innovation"],
    mentorYears: [3, 4, 5, 8, 9],
  },
  {
    id: "mentor-19",
    mentorPictureUrl: "/mentors/mentor-19.jpg",
    nickname: "พี่ที",
    fullName: "นที จรัสสุริยงค์",
    department: "NANO",
    classYear: 90,
    position: "Co-Founder",
    companyName: "Guss Damn Good",
    industries: ["entrepreneur-and-start-up", "food-and-beverage"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-20",
    mentorPictureUrl: "/mentors/mentor-20.jpg",
    nickname: "พี่เปิ้ล",
    fullName: "วิลาวัณย์ อติวัฒนานนท์",
    department: "ME",
    classYear: 75,
    position: "Business Development Director",
    companyName: "ฟาร์มาซูติคอลส์ แอนด์ เมดิคอลซัพพลาย (PMS)",
    industries: ["manufacturing", "food-and-beverage"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-21",
    mentorPictureUrl: "/mentors/mentor-21.jpg",
    nickname: "พี่ภูมิ",
    fullName: "ธนวัฒน์ ชิวหวรรณ",
    department: "PETRO",
    classYear: 95,
    position: "CEO & Co-Founder",
    companyName: "Tokenomist",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up", "financial-and-investment"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-22",
    mentorPictureUrl: "/mentors/mentor-22.png",
    nickname: "พี่ติ๊",
    fullName: "ภีรติ ศรัทธา",
    department: "IE",
    classYear: 88,
    position: "VP of Retail & FMCG Business",
    companyName: "GQ Group",
    industries: ["manufacturing", "commercial-and-marketing"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-23",
    mentorPictureUrl: "/mentors/mentor-23.jpg",
    nickname: "พี่ตาม",
    fullName: "กุลฉัตร ธาราจันทร์",
    department: "AE",
    classYear: 79,
    position: "Senior Vice President, Plant Head bangkok",
    companyName: "Pandora Production Thailand",
    industries: ["engineering", "manufacturing"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-24",
    mentorPictureUrl: "/mentors/mentor-24.jpg",
    nickname: "พี่เอก",
    fullName: "เอกรินทร์ ชินบุตรานนท์",
    department: "IE",
    classYear: 88,
    position: "Manufacturing and Digital Capability Transformation Director",
    companyName: "Procter & Gamble",
    industries: ["tech-and-innovation", "manufacturing"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-25",
    mentorPictureUrl: "/mentors/mentor-25.jpg",
    nickname: "พี่อ้น",
    fullName: "เฉลิมวุฒิ ชมะนันทน์",
    department: "CP",
    classYear: 81,
    position: "Chief Operations Officer",
    companyName: "KKP Dime",
    industries: ["financial-and-investment"],
    mentorYears: [9],
  },
  {
    id: "mentor-26",
    mentorPictureUrl: "/mentors/mentor-26.jpg",
    nickname: "พี่แอ๊กกี้",
    fullName: "เอกพล ณ สงขลา",
    department: "EE",
    classYear: 70,
    position: "Chief People Officer and Head of Strategy",
    companyName: "Thai Group Holdings",
    industries: ["financial-and-investment"],
    mentorYears: [8, 9],
  },
  {
    id: "mentor-27",
    mentorPictureUrl: "/mentors/mentor-27.jpg",
    nickname: "พี่ยิม",
    fullName: "วงศ์กนก กนกธนาพร",
    department: "IE",
    classYear: 87,
    position: "Production Manager",
    companyName: "SCGP",
    industries: ["manufacturing"],
    mentorYears: [7, 8, 9],
  },
  {
    id: "mentor-28",
    mentorPictureUrl: "/mentors/mentor-28.jpeg",
    nickname: "พี่ต้น",
    fullName: "อครินทร์ ภูรีสิทธิ์",
    department: "ME",
    classYear: 73,
    position: "Chief People Officer",
    companyName: "Central Pattana (CPN)",
    industries: ["commercial-and-marketing"],
    mentorYears: [5, 6, 7],
  },
  {
    id: "mentor-29",
    mentorPictureUrl: "/mentors/mentor-29.jpg",
    nickname: "พี่ฮี",
    fullName: "ธาริต นิมมานวุฒิพงษ์",
    department: "CHEM",
    classYear: 86,
    position: "GM",
    companyName: "True Digital Park",
    industries: ["tech-and-innovation"],
    mentorYears: [7],
  },
  {
    id: "mentor-30",
    mentorPictureUrl: "/mentors/mentor-30.png",
    nickname: "พี่แซม",
    fullName: "อดิศัย ธรรมร่มดี",
    department: "IE",
    classYear: 88,
    position: "Head of Personal Care Sector",
    companyName: "Google Thailand",
    industries: ["tech-and-innovation"],
    mentorYears: [5, 6, 7],
  },
  {
    id: "mentor-31",
    mentorPictureUrl: "/mentors/mentor-31.png",
    nickname: "พี่ไกด์",
    fullName: "เปรมปรีดี กิติรัตน์ตระการ",
    department: "EE",
    classYear: 88,
    position: "ผู้จัดการ โครงการ ExpresSo",
    companyName: "บริษัท ปตท. จำกัด (มหาชน)",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7],
  },
  {
    id: "mentor-32",
    mentorPictureUrl: "/mentors/mentor-32.jpg",
    nickname: "พี่กวาง",
    fullName: "ณัฐธิดา เจริญเกียรติบวร",
    department: "MET",
    classYear: 91,
    position: "Regional Head of Digital Media",
    companyName: "Intrepid",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [7, 8],
  },
  {
    id: "mentor-33",
    mentorPictureUrl: "/mentors/mentor-33.jpg",
    nickname: "พี่พลอย",
    fullName: "ณภัทร วิชชาบุญศิริ",
    department: "NANO",
    classYear: 94,
    position: "Head of Payment Platform Optimization, Strategy and Business Innovation",
    companyName: "True Money Thailand",
    industries: ["tech-and-innovation"],
    mentorYears: [7],
  },
  {
    id: "mentor-34",
    mentorPictureUrl: "/mentors/mentor-34.jpeg",
    nickname: "พี่รัมย์",
    fullName: "ดร. ศรุต วานิชพันธ์ุ",
    department: "EE",
    classYear: 79,
    position: "Senior Director",
    companyName: "Sea (Thailand)",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-35",
    mentorPictureUrl: "/mentors/mentor-35.jpg",
    nickname: "พี่นิค",
    fullName: "สมิทธ์ พนมยงค์",
    department: "IE",
    classYear: 73,
    position: "Executive Officer",
    companyName: "Gulf Energy Development",
    industries: ["engineering"],
    mentorYears: [1, 2, 4, 5, 7],
  },
  {
    id: "mentor-36",
    mentorPictureUrl: "/mentors/mentor-36.jpg",
    nickname: "พี่เหมียว",
    fullName: "พรรสิฐฏ์ จิตสอาดกุล",
    department: "CIVIL",
    classYear: 86,
    position: "Founder , MD loop",
    companyName: "MP Synergy Co.,Ltd. , Ergotrend Brand",
    industries: ["commercial-and-marketing", "entrepreneur-and-start-up"],
    mentorYears: [7, 8],
  },
  {
    id: "mentor-37",
    mentorPictureUrl: "/mentors/mentor-37.jpg",
    nickname: "พี่โหน่ง Learn",
    fullName: "สุธี อัสววิมล",
    department: "IE",
    classYear: 78,
    position: "Board of director",
    companyName: "LEARN Corporation",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7],
  },
  {
    id: "mentor-38",
    mentorPictureUrl: "/mentors/mentor-38.png",
    nickname: "พี่แม็ก",
    fullName: "ศิวดล มาตยากูร",
    department: "EE",
    classYear: 88,
    position: "Co-founder Cariva",
    companyName: "CARIVA",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [7],
  },
  {
    id: "mentor-39",
    mentorPictureUrl: "/mentors/mentor-39.jpeg",
    nickname: "พี่โจโจ้",
    fullName: "วชิระชัย คูนำวัฒนา",
    department: "ME",
    classYear: 71,
    position: "Head of Smart System Solution Business",
    companyName: "SCG Smart Living",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7],
  },
  {
    id: "mentor-40",
    mentorPictureUrl: "/mentors/mentor-40.jpeg",
    nickname: "พี่สปริง",
    fullName: "พิสิษฐ์ ธนเศรษฐ์สกุล",
    department: "ADME",
    classYear: 92,
    position: "Chief Business Officer",
    companyName: "บริษัท ริพเพิลส์คอมเมิร์ซ จำกัด",
    industries: ["commercial-and-marketing"],
    mentorYears: [5, 6, 7],
  },
  {
    id: "mentor-41",
    mentorPictureUrl: "/mentors/mentor-41.jpeg",
    nickname: "พี่กุ๊ก",
    fullName: "ดร.กนกพัฒน์ ชาญไววิทย์",
    department: "CIVIL",
    classYear: 80,
    position: "Technical Director",
    companyName: "Bouygues Thai Ltd.",
    industries: ["engineering"],
    mentorYears: [6, 7],
  },
  {
    id: "mentor-42",
    mentorPictureUrl: "/mentors/mentor-42.jpeg",
    nickname: "พี่ปู",
    fullName: "สุรัตน์ ประลองศิลป์",
    department: "IE",
    classYear: 72,
    position: "ประธานคณะกรรมการตรวจสอบ, บมจ. เซปเป้",
    companyName: "Sappe",
    industries: ["engineering", "financial-and-investment"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-43",
    mentorPictureUrl: "/mentors/mentor-43.jpg",
    nickname: "พี่บุ๊น",
    fullName: "เกียรติยศ พานิชปรีชา",
    department: "CP",
    classYear: 86,
    position: "Founder&CEO",
    companyName: "bit.studio",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [7],
  },
  {
    id: "mentor-44",
    mentorPictureUrl: "/mentors/mentor-44.jpeg",
    nickname: "พี่โหน่ง",
    fullName: "วรคุณ บุญโสธรสถิตย์",
    department: "IE",
    classYear: 72,
    position: "Managing Director",
    companyName: "บริษัท พาราแอดวานซ์อินโฟเทค จำกัด (ทำ enterprise IT solutions)",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7],
  },
  {
    id: "mentor-45",
    mentorPictureUrl: "/mentors/mentor-45.jpg",
    nickname: "พี่บูน",
    fullName: "ปิธน วิทยศรีเจริญ",
    department: "CIVIL",
    classYear: 81,
    position: "Managing Director",
    companyName: "Digital Health Venture, Samitivej",
    industries: ["tech-and-innovation"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-46",
    mentorPictureUrl: "/mentors/mentor-46.jpeg",
    nickname: "พี่ต้อง",
    fullName: "กวีวุฒิ เต็มภูวภัทร",
    department: "PETRO",
    classYear: 86,
    position: "CEO",
    companyName: "SCB10X",
    industries: ["financial-and-investment"],
    mentorYears: [1, 2, 6, 7, 8],
  },
  {
    id: "mentor-47",
    mentorPictureUrl: "/mentors/mentor-47.jpg",
    nickname: "พี่เบนซ์",
    fullName: "วรภัทร ชวนะนิกุล",
    department: "ME",
    classYear: 79,
    position: "CEO",
    companyName: "Singha Ventures; CFO/ CSO Boonrawd Trading; Partner, BMB Capital",
    industries: ["food-and-beverage", "financial-and-investment"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-48",
    mentorPictureUrl: "/mentors/mentor-48.jpg",
    nickname: "พี่เอิร์ธ",
    fullName: "ดร. รัฐศรัณย์ ธนไพศาลกิจ",
    department: "IE",
    classYear: 89,
    position: "Head of Investment Strategy & Trading Products",
    companyName: "InnovestX Securities Co.,Ltd.",
    industries: ["financial-and-investment"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-49",
    mentorPictureUrl: "/mentors/mentor-49.jpg",
    nickname: "พี่เหน่ง",
    fullName: "ปกรณ์ ธรรมภิมุขวัฒนา",
    department: "ME",
    classYear: 79,
    position: "Supply Chain Director",
    companyName: "Danone Specialized Nutrition",
    industries: ["manufacturing", "food-and-beverage"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-50",
    mentorPictureUrl: "/mentors/mentor-50.jpg",
    nickname: "พี่ปะ",
    fullName: "ปพนธ์ มังคละธนะกุล",
    department: "IE",
    classYear: 72,
    position: "Founder & CEO",
    companyName: "PI Carbon Co., Ltd.",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [6, 7, 8],
  },
  {
    id: "mentor-51",
    mentorPictureUrl: "/mentors/mentor-51.jpg",
    nickname: "พี่เกด",
    fullName: "การะเกด เกษชุมพล",
    department: "EE",
    classYear: 79,
    position: "Solutions Engineer",
    companyName: "Cisco Systems(Thailand)",
    industries: ["engineering"],
    mentorYears: [7],
  },
  {
    id: "mentor-52",
    mentorPictureUrl: "/mentors/mentor-52.jpg",
    nickname: "พี่ปันเจ",
    fullName: "ปัญจมพงศ์ เสริมสวัสดิ์ศรี",
    department: "CP",
    classYear: 92,
    position: "Chief Technology Officer",
    companyName: "Clerverse",
    industries: ["tech-and-innovation"],
    mentorYears: [2, 3, 5, 6],
  },
  {
    id: "mentor-53",
    mentorPictureUrl: "/mentors/mentor-53.jpg",
    nickname: "พี่ธัช",
    fullName: "กิตติธัช อภิศักดิ์ศิริกุล",
    department: "ICE",
    classYear: 93,
    position: "Chief Operating Officer",
    companyName: "Mercular",
    industries: ["commercial-and-marketing"],
    mentorYears: [2, 3, 4, 5, 6],
  },
  {
    id: "mentor-54",
    mentorPictureUrl: "/mentors/mentor-54.jpg",
    nickname: "พี่ยีราฟ",
    fullName: "สรวิศ ไพบูลย์รัตนากร",
    department: "CP",
    classYear: 92,
    position: "Founder & CEO",
    companyName: "Saturday School Foundation",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [4, 5, 6],
  },
  {
    id: "mentor-55",
    mentorPictureUrl: "/mentors/mentor-55.jpeg",
    nickname: "พี่วี",
    fullName: "วีรวัฒน์ คิรินทร์รัตนะ",
    department: "IE",
    classYear: 88,
    position: "Head of Distribution Sales",
    companyName: "Amundi Asset Management",
    industries: ["commercial-and-marketing", "financial-and-investment"],
    mentorYears: [1, 2, 3, 4, 5, 6],
  },
  {
    id: "mentor-56",
    mentorPictureUrl: "/mentors/mentor-56.jpg",
    nickname: "พี่มาร์ช",
    fullName: "ธีรพงศ์ มหธรรม",
    department: "CP",
    classYear: 79,
    position: "Managing Director",
    companyName: "Krungsri Nimble",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [6],
  },
  {
    id: "mentor-57",
    mentorPictureUrl: "/mentors/mentor-57.jpg",
    nickname: "พี่เอ็ม",
    fullName: "ธนวัฒน์ ว่องเศรษฐชัย",
    department: "IE",
    classYear: 91,
    position: "Regional Industrial Engineering manager - Asia",
    companyName: "Mars Petcare",
    industries: ["engineering", "manufacturing", "food-and-beverage"],
    mentorYears: [2, 3, 4, 6],
  },
  {
    id: "mentor-58",
    mentorPictureUrl: "/mentors/mentor-58.jpeg",
    nickname: "พี่เล้ง",
    fullName: "ศิริวัฒน์ วงศ์จารุกร",
    department: "CP",
    classYear: 70,
    position: "CEO",
    companyName: "MFEC (Public company Limited)",
    industries: ["tech-and-innovation"],
    mentorYears: [1, 2, 3, 4, 5, 6],
  },
  {
    id: "mentor-59",
    mentorPictureUrl: "/mentors/mentor-59.jpeg",
    nickname: "พี่เจียง",
    fullName: "ดร.ชวพล จริยาวิโรจน์",
    department: "IE",
    classYear: 70,
    position: "President",
    companyName: "Huawei Technologies Thailand",
    industries: ["tech-and-innovation", "engineering"],
    mentorYears: [1, 2, 6],
  },
  {
    id: "mentor-60",
    mentorPictureUrl: "/mentors/mentor-60.jpeg",
    nickname: "พี่เหมา",
    fullName: "วิษณุ วิวัฒนะประเสริฐ",
    department: "CIVIL",
    classYear: 73,
    position: "กรรมการผู้จัดการ",
    companyName: "บริษัท อัลเท็มเทค จำกัด",
    industries: ["engineering"],
    mentorYears: [2, 3, 4, 5, 6],
  },
  {
    id: "mentor-61",
    mentorPictureUrl: "/mentors/mentor-61.jpeg",
    nickname: "พี่ไปร้",
    fullName: "พิชิต พงษ์ประเสริฐ",
    department: "EE",
    classYear: 81,
    position: "หัวหน้าทีมธุรกิจยานยนต์ไฟฟ้า",
    companyName: "การไฟฟ้าฝ่ายผลิตแห่งประเทศไทย",
    industries: ["engineering"],
    mentorYears: [4, 5, 6],
  },
  {
    id: "mentor-62",
    mentorPictureUrl: "/mentors/mentor-62.jpg",
    nickname: "พี่เก้",
    fullName: "มณฑิชา ด่านชลวิจิตร",
    department: "CHEM",
    classYear: 79,
    position: "Head of Innovation Management",
    companyName: "Osotspa Public Company Limited",
    industries: ["food-and-beverage"],
    mentorYears: [6],
  },
  {
    id: "mentor-63",
    mentorPictureUrl: "/mentors/mentor-63.jpeg",
    nickname: "พี่เจมส์ จิมมี่",
    fullName: "จีรวัฒน์ สิทธิ์สันต์กุล",
    department: "CHEM",
    classYear: 80,
    position: "Chief Marketing Officer",
    companyName: "NBD Healthcare (VISTRA)",
    industries: ["commercial-and-marketing"],
    mentorYears: [6],
  },
  {
    id: "mentor-64",
    mentorPictureUrl: "/mentors/mentor-64.jpeg",
    nickname: "พี่แนท",
    fullName: "ชลิยา จุลโมกข์ สุชาโต",
    department: "IE",
    classYear: 78,
    position: "Asia Strategic Demand Director",
    companyName: "Mars",
    industries: ["commercial-and-marketing", "food-and-beverage"],
    mentorYears: [6],
  },
  {
    id: "mentor-65",
    mentorPictureUrl: "/mentors/mentor-65.jpg",
    nickname: "พี่หวัง",
    fullName: "กิตติศักดิ์ ปัญญาจิรกุล",
    department: "AE",
    classYear: 88,
    position: "Business Development Director",
    companyName: "Sertis",
    industries: ["tech-and-innovation"],
    mentorYears: [3, 4, 5, 6],
  },
  {
    id: "mentor-66",
    mentorPictureUrl: "/mentors/mentor-66.jpg",
    nickname: "พี่แกม",
    fullName: "แกมแพร ศุภกรโกศัย",
    department: "IE",
    classYear: 87,
    position: "Client Partner",
    companyName: "Meta Thailand",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [4, 5, 6],
  },
  {
    id: "mentor-67",
    mentorPictureUrl: "/mentors/mentor-67.jpg",
    nickname: "พี่ก้อง",
    fullName: "กฤตภาส สิริภัสสร",
    department: "IE",
    classYear: 78,
    position: "Head of Business Intelligence",
    companyName: "CP",
    industries: ["financial-and-investment"],
    mentorYears: [6],
  },
  {
    id: "mentor-68",
    mentorPictureUrl: "/mentors/mentor-68.jpg",
    nickname: "พี่พร้อม",
    fullName: "ถึงพร้อม มณีรอด",
    department: "IE",
    classYear: 86,
    position: "Supply Chain Director - Head of Thailand Supply Chain",
    companyName: "Procter & Gamble",
    industries: ["manufacturing"],
    mentorYears: [6],
  },
  {
    id: "mentor-69",
    mentorPictureUrl: "/mentors/mentor-69.png",
    nickname: "พี่อ้อ",
    fullName: "รัชดา ด่านพงษ์เจริญ",
    department: "ENVI",
    classYear: 79,
    position: "Principal - Digital Banking & Head of Juristic Omnichannel",
    companyName: "SCB",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [3, 4, 5, 6],
  },
  {
    id: "mentor-70",
    mentorPictureUrl: "/mentors/mentor-70.jpg",
    nickname: "พี่โทนี่",
    fullName: "โทนี่ คันธาภัสระ",
    department: "IE",
    classYear: 88,
    position: "Managing Director",
    companyName: "Willis Towers Watson",
    industries: ["financial-and-investment"],
    mentorYears: [3, 4, 5, 6],
  },
  {
    id: "mentor-71",
    mentorPictureUrl: "/mentors/mentor-71.jpg",
    nickname: "พี่เบสท์",
    fullName: "อภินาถ คุณานพรัตน์",
    department: "IE",
    classYear: 89,
    position: "Regional Director",
    companyName: "SnapLogic",
    industries: ["tech-and-innovation"],
    mentorYears: [4, 5, 6],
  },
  {
    id: "mentor-72",
    mentorPictureUrl: "/mentors/mentor-72.jpg",
    nickname: "พี่ณัฐ",
    fullName: "ณัฐวุฒิ อมรวิวัฒน์",
    department: "EE",
    classYear: 73,
    position: "Chairman of True Digital Group and Board of Director of True Corp, Ascend Money, True IDC",
    companyName: "True Corporation (public) Company Limited",
    industries: ["tech-and-innovation"],
    mentorYears: [2, 5, 8],
  },
  {
    id: "mentor-73",
    mentorPictureUrl: "/mentors/mentor-73.jpg",
    nickname: "พี่หลุยส์",
    fullName: "ธีรพจน์ จรสโรจน์กุล",
    department: "IE",
    classYear: 78,
    position: "Supervisor Board, ROC Spicer Ltd. Taiwan, Plant Manager, Dana Spicer (Thailand)",
    companyName: "Dana Spicer",
    industries: ["engineering"],
    mentorYears: [1, 2, 3, 4, 8],
  },
  {
    id: "mentor-74",
    mentorPictureUrl: "/mentors/mentor-74.jpg",
    nickname: "พี่ช้าง",
    fullName: "มหิศร ว่องผาติ",
    department: "CP",
    classYear: 84,
    position: "Founder",
    companyName: "HG Robotics Co., Ltd.",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [1, 2, 8],
  },
  {
    id: "mentor-75",
    mentorPictureUrl: "/mentors/mentor-75.jpg",
    nickname: "พี่โอ๊ต",
    fullName: "วรวรรณ ไชยกำเนิด",
    department: "ME",
    classYear: 76,
    position: "ex CEO, ex Director",
    companyName: "Rojukiss International PCL",
    industries: ["manufacturing"],
    mentorYears: [8],
  },
  {
    id: "mentor-76",
    mentorPictureUrl: "/mentors/mentor-76.webp",
    nickname: "พี่เบนซ์",
    fullName: "สัมฤทธิ์ สิทธิวรานุวงศ์",
    department: "ME",
    classYear: 83,
    position: "Chief Executive Officer & Founder",
    companyName: "Solar D Corporation Co., Ltd.",
    industries: ["engineering", "entrepreneur-and-start-up"],
    mentorYears: [8],
  },

  // ---------------------------------------------------------------------------
  // mentor-77..127 — ChAMP 1-5 only, from the "ChAMP Eng mentor" Google Sheet.
  // No photo and no company logo exist for anyone below. `department` and
  // `classYear` are present only where a ChAMP year tab recorded them; see the
  // "ChAMP 1-5 caveats" note at the top of this file.
  // ---------------------------------------------------------------------------
  {
    id: "mentor-77",
    nickname: "พี่ก้อง",
    fullName: "พณชิต กิตติปัญญางาม",
    department: "EE",
    classYear: 78,
    position: "CEO",
    companyName: "AccRevo",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [1, 2, 3, 4, 5],
  },
  {
    id: "mentor-78",
    nickname: "พี่ก๊วย",
    fullName: "ไพโรจน์ กวียานันท์",
    department: "PETRO",
    classYear: 68,
    position: "Retired executive",
    companyName: "Chevron Thailand Exploration and Production Ltd.",
    industries: ["engineering"],
    mentorYears: [1, 2, 3, 4, 5],
  },
  {
    id: "mentor-79",
    nickname: "พี่ต้า",
    fullName: "ดร. วิโรจน์ จิรพัฒนกุล",
    department: "CP",
    classYear: 87,
    position: "กรรมการผู้จัดการ",
    companyName: "บริษัท สคูลดิโอ จำกัด",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [1, 2, 3, 4, 5],
  },
  {
    id: "mentor-80",
    nickname: "พี่วิน",
    fullName: "วิธวินท์ อิทธิภาณุวัต",
    department: "CP",
    classYear: 90,
    position: "Executive Director",
    companyName: "Vertex Ventures",
    industries: ["financial-and-investment", "entrepreneur-and-start-up"],
    mentorYears: [1, 2, 3, 4],
  },
  {
    id: "mentor-81",
    nickname: "พี่โบ้",
    fullName: "พิเชษฐ สิทธิอำนวย",
    department: "IE",
    classYear: 67,
    position: "กรรมการผู้อำนวยการ",
    companyName: "บริษัท หลักทรัพย์ บัวหลวง จำกัด (มหาชน)",
    industries: ["financial-and-investment"],
    mentorYears: [1, 2, 3, 4],
  },
  {
    id: "mentor-82",
    nickname: "พี่เส",
    fullName: "เสนธิป ศรีไพพรรณ",
    department: "IE",
    classYear: 72,
    position: "Chief Commercial Banking Officer",
    companyName: "TMB Thanachart Bank",
    industries: ["financial-and-investment"],
    mentorYears: [1, 2, 3, 4],
  },
  {
    id: "mentor-83",
    nickname: "พี่ต้น",
    fullName: "วงศกร ชัยวนนท์",
    department: "EE",
    classYear: 87,
    position: "Executive Vice President, Data Analytics",
    companyName: "SCB",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [1, 2, 3, 5],
  },
  {
    id: "mentor-84",
    nickname: "พี่ต้อง",
    fullName: "สโรชินี ปวีณวัฒน์",
    department: "CP",
    classYear: 83,
    position: "Assistant Managing Director",
    companyName: "Dplus Intertrade co., ltd.",
    industries: ["commercial-and-marketing"],
    mentorYears: [1, 2, 3],
  },
  {
    id: "mentor-85",
    nickname: "พี่โอม",
    fullName: "อัฐพงศ์ รัตนวีระชานน",
    department: "CP",
    classYear: 91,
    position: "Head Coder",
    companyName: "Finnomena",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [1, 2, 3],
  },
  {
    id: "mentor-86",
    nickname: "พี่ประทิต",
    fullName: "ประทิต โลหะธีรภาพ",
    department: "CHEM",
    classYear: 71,
    position: "Vice President",
    companyName: "PTT Global Chemical Plc.",
    industries: ["engineering", "manufacturing"],
    mentorYears: [1, 2, 3],
  },
  {
    id: "mentor-87",
    nickname: "พี่โหน่ง",
    fullName: "พิสิฐ ยิ่งมโนกิจ",
    department: "CIVIL",
    classYear: 78,
    position: "Executive Director, Co-founder",
    companyName: "InGen Design",
    industries: ["engineering", "entrepreneur-and-start-up"],
    mentorYears: [1, 2, 3],
  },
  {
    id: "mentor-88",
    nickname: "พี่ฟอง",
    fullName: "อรรถสิทธิ์ พานิชย์ไพศาลกูล",
    department: "CHEM",
    classYear: 87,
    position: "ผู้จัดการส่วนการลงทุนต่างประเทศ",
    companyName: "PTT Global Chemical Plc.",
    industries: ["engineering", "manufacturing", "financial-and-investment"],
    mentorYears: [1, 2, 3],
  },
  {
    id: "mentor-89",
    nickname: "พี่ชาญ",
    fullName: "ดร.พลภัทร์ อุดมผล",
    department: "EE",
    classYear: 78,
    position: "ผู้ร่วมก่อตั้ง และผู้อำนวยการฝ่ายพัฒนาธุรกิจ",
    companyName: "บริษัท อุ๊คบี จำกัด",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-90",
    nickname: "พี่ทริป",
    fullName: "รศ.ดร. ชัชชาติ สิทธิพันธุ์",
    department: "CIVIL",
    classYear: 67,
    // The sheet still had him at Quality Houses, which he left in 2022.
    // Governor of Bangkok since May 2022, re-elected 28 June 2026.
    position: "ผู้ว่าราชการกรุงเทพมหานคร",
    companyName: "กรุงเทพมหานคร",
    industries: ["engineering"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-91",
    nickname: "พี่ก้อง",
    fullName: "ก้องกิติ ลิ่วเจริญชัย",
    department: "ME",
    classYear: 87,
    position: "Assistant Business Venturing Manager",
    companyName: "SCG",
    industries: ["manufacturing", "entrepreneur-and-start-up"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-92",
    nickname: "พี่เล็ก",
    fullName: "รุ่งโรจน์ ตันเจริญ",
    department: "IE",
    classYear: 90,
    position: "กรรมการผู้จัดการ",
    companyName: "Rabbit Group",
    industries: ["commercial-and-marketing", "financial-and-investment"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-93",
    nickname: "พี่ที",
    fullName: "ไพที สกุลเอี่ยมไพบูลย์",
    department: "IE",
    classYear: 79,
    position: "รองกรรมการผู้จัดการสายงานโลจิสติกส์",
    companyName: "บุญถาวร เซรามิค",
    industries: ["manufacturing", "commercial-and-marketing"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-94",
    nickname: "พี่โบ๊ท",
    fullName: "ไผท ผดุงถิ่น",
    department: "CIVIL",
    classYear: 80,
    position: "ผู้ก่อตั้ง และกรรมการผู้จัดการ",
    companyName: "บริษัท บิลค์ เอเชีย จำกัด",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-95",
    nickname: "พี่ศา",
    fullName: "ศานนท์ หวังสร้างบุญ",
    department: "IE",
    classYear: 91,
    position: "Owner",
    companyName: "Once again Hostel",
    industries: ["entrepreneur-and-start-up"],
    mentorYears: [1, 2],
  },
  {
    id: "mentor-96",
    nickname: "พี่หลุยส์",
    fullName: "อัมรินทร์ สิมะโรจน์",
    department: "EE",
    classYear: 78,
    position: "รองกรรมการผู้จัดการสายงานบริหาร",
    companyName: "Susco",
    industries: ["engineering", "commercial-and-marketing"],
    mentorYears: [1, 4],
  },
  {
    id: "mentor-97",
    nickname: "พี่ชาญยุทธ",
    fullName: "ชาญยุทธ ฉายาวัฒนะ",
    department: "ME",
    classYear: 64,
    position: "Deputy CEO",
    companyName: "Energy Solution Management",
    industries: ["engineering"],
    mentorYears: [1],
  },
  {
    id: "mentor-98",
    nickname: "พี่ยอด",
    fullName: "ยอด ชินสุภัคกุล",
    department: "CP",
    classYear: 84,
    position: "กรรมการผู้จัดการ",
    companyName: "Wongnai",
    industries: [
      "tech-and-innovation",
      "entrepreneur-and-start-up",
      "food-and-beverage",
    ],
    mentorYears: [1],
  },
  {
    id: "mentor-99",
    nickname: "พี่แมน",
    fullName: "วีรทศ สิมะพิชัยเชษฐ",
    department: "IE",
    classYear: 79,
    position: "กรรมการผู้จัดการ",
    companyName: "UBS",
    industries: ["financial-and-investment"],
    mentorYears: [1],
  },
  {
    id: "mentor-100",
    nickname: "พี่โอม",
    fullName: "วรวิทย์ ชื่นชีพ",
    department: "CHEM",
    classYear: 88,
    position: "Senior Technical Support Engineer",
    companyName: "PTTGC",
    industries: ["engineering", "manufacturing"],
    mentorYears: [1],
  },
  {
    id: "mentor-101",
    nickname: "พี่เทิดศักดิ์",
    fullName: "เทิดศักดิ์ ฤกษ์ประเสริฐกุล",
    department: "CHEM",
    classYear: 82,
    position: "Division Manager",
    companyName: "PTT Global Chemical Plc.",
    industries: ["engineering", "manufacturing"],
    mentorYears: [1],
  },
  {
    id: "mentor-102",
    nickname: "พี่นาถ",
    fullName: "ศิรินาถ ตั้งรวมทรัพย์",
    department: "CP",
    classYear: 86,
    position: "Data Scientist",
    companyName: "Agoda",
    industries: ["tech-and-innovation"],
    mentorYears: [1],
  },
  {
    id: "mentor-103",
    nickname: "พี่สมคิด",
    fullName: "สมคิด จิรานันตรัตน์",
    department: "CP",
    classYear: 65,
    position: "ประธาน",
    companyName: "Kasikorn Business-Technology Group",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [1],
  },
  {
    id: "mentor-104",
    nickname: "พี่ธนญ",
    fullName: "ธนญ ตันติสุนทร",
    department: "ENVI",
    classYear: 74,
    position: "ผู้ช่วยกรรมการผู้จัดการใหญ่ กลุ่มงานองค์กรสัมพันธ์",
    companyName: "บริษัท กัลฟ์ เอ็นเนอร์จี ดีเวลลอปเมนท์ จำกัด (มหาชน)",
    industries: ["engineering"],
    mentorYears: [1],
  },
  {
    id: "mentor-105",
    nickname: "พี่บุริศวร์",
    fullName: "บุริศวร์ กิตติรังสิ",
    department: "AE",
    classYear: 80,
    position: "Vice President - Head of Digital Lending Analytics",
    companyName: "KBank",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [1],
  },
  {
    id: "mentor-106",
    nickname: "พี่แบงก์",
    fullName: "ฐิติพงศ์ รัตนหิรัญญา",
    department: "CHEM",
    classYear: 86,
    position: "Asia Process Development Manager",
    companyName: "Mars Petcare",
    industries: ["engineering", "manufacturing", "food-and-beverage"],
    mentorYears: [2, 3, 4, 5],
  },
  {
    id: "mentor-107",
    nickname: "พี่โน",
    fullName: "อโณทัย อดุลพันธุ์",
    department: "IE",
    classYear: 73,
    position: "Managing Partner",
    companyName: "Lakeshore Capital Partners",
    industries: ["financial-and-investment"],
    mentorYears: [2, 3, 4, 5],
  },
  {
    id: "mentor-108",
    nickname: "พี่โบ๊ท",
    fullName: "ภัทรวิน จงวิศาล",
    department: "NAVAL",
    classYear: 84,
    position: "ประธานเจ้าหน้าที่บริหาร",
    companyName: "บริษัท มาร์ซัน จำกัด (มหาชน)",
    industries: ["engineering", "manufacturing"],
    mentorYears: [2, 3, 5],
  },
  {
    id: "mentor-109",
    nickname: "พี่ไมเคิล",
    fullName: "อธิวรรธน์ วงศ์ไวศยวรรณ",
    department: "IE",
    classYear: 79,
    position:
      "Director (CEO Office) and Sustainable Development Committee",
    companyName: "CJ Express Group",
    industries: ["commercial-and-marketing"],
    mentorYears: [2, 3, 5],
  },
  {
    id: "mentor-110",
    nickname: "พี่เอ้",
    fullName: "ศรัณย์ ผโลประการ",
    department: "EE",
    position: "Head of Fixed Broadband",
    companyName: "AIS",
    industries: ["tech-and-innovation"],
    mentorYears: [2],
  },
  {
    id: "mentor-111",
    nickname: "พี่ใหม่",
    fullName: "ปริมล กาญจนจารี",
    department: "CP",
    // Conflict: ChAMP 3 tab says Intania 80, ChAMP 4 + 5 tabs say 78.
    // Later year wins, per the merge rules above.
    classYear: 78,
    position: "Partner",
    companyName: "McKinsey & Company",
    industries: ["commercial-and-marketing", "financial-and-investment"],
    mentorYears: [3, 4, 5],
  },
  {
    id: "mentor-112",
    nickname: "พี่เก่ง",
    fullName: "ดร.ธิติ วัชรสินธพชัย",
    department: "CIVIL",
    classYear: 78,
    position: "SVP",
    companyName: "Team Group",
    industries: ["engineering", "tech-and-innovation"],
    mentorYears: [3, 4, 5],
  },
  {
    id: "mentor-113",
    nickname: "พี่ตั้ม",
    fullName: "สันติ ศรีวิชาญกุล",
    department: "ME",
    classYear: 77,
    position: "กรรมการผู้จัดการใหญ่",
    companyName: "บริษัท ซี.ไอ.ที. จำกัด (KUDOS)",
    industries: ["manufacturing", "commercial-and-marketing"],
    mentorYears: [3, 4, 5],
  },
  {
    id: "mentor-114",
    nickname: "พี่เหมย",
    fullName: "ศิรินทร์ เจ้าพิทักษ์วงศ์",
    department: "ME",
    classYear: 84,
    position: "ผู้ช่วยผู้จัดการทั่วไป",
    companyName: "บริษัท ซิตี้ไลอ้อนสตีม จำกัด",
    industries: ["engineering", "manufacturing"],
    mentorYears: [3, 4],
  },
  {
    id: "mentor-115",
    nickname: "พี่เห่า",
    fullName: "ดร.วิบูลย์ อรุณธเนศ",
    department: "CP",
    classYear: 63,
    position: "Chief Executive Officer",
    companyName: "CCM Spirit Co., Ltd",
    industries: ["food-and-beverage"],
    mentorYears: [3, 4],
  },
  {
    id: "mentor-116",
    nickname: "พี่ต้อง",
    fullName: "อโณทัย รัตนกุล",
    department: "EE",
    classYear: 73,
    position: "รองหัวหน้าคณะผู้บริหารด้านการบริการลูกค้า",
    companyName: "บริษัท ทรู คอเปอเรชั่น จำกัด (มหาชน)",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [3, 4],
  },
  {
    id: "mentor-117",
    nickname: "พี่หยก",
    fullName: "บุญญพร ฤทธิเดช",
    department: "ME",
    classYear: 84,
    position: "Managing Director",
    companyName: "Soecon Engineering Co,m Ltd.",
    industries: ["engineering", "manufacturing"],
    mentorYears: [3],
  },
  {
    id: "mentor-118",
    nickname: "พี่ถิ",
    fullName: "ถิรพันธุ์ สรรพกิจ",
    department: "CP",
    classYear: 73,
    position: "รองผู้จัดการ สายงานเทคโนโลยีสารสนเทศ",
    companyName: "SET",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [3],
  },
  {
    id: "mentor-119",
    nickname: "พี่รุจ",
    fullName: "ดร. รุจ ณ สงขลา",
    department: "ME",
    classYear: 73,
    position: "กรรมการผู้จัดการ",
    companyName: "บริษัท เอสอาร์ แอดวานซ์อินดัสตรีส์ จำกัด",
    industries: ["engineering", "manufacturing"],
    mentorYears: [3],
  },
  {
    id: "mentor-120",
    nickname: "พี่โอห์ม",
    fullName: "กิตติชัย จิรสุขานนท์",
    department: "CP",
    classYear: 78,
    position: "Managing Director / CEO",
    companyName: "Cleverse Co Ltd",
    industries: ["tech-and-innovation", "entrepreneur-and-start-up"],
    mentorYears: [4, 5],
  },
  {
    id: "mentor-121",
    nickname: "พี่โบ๊ท",
    fullName: "พชร อารยะการกุล",
    department: "CP",
    classYear: 89,
    position: "ประธานเจ้าหน้าที่บริหาร",
    companyName: "บลูบิค กรุ๊ป จำกัด (มหาชน)",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [4, 5],
  },
  {
    id: "mentor-122",
    nickname: "พี่เต๋อ",
    fullName: "สาธร อุพันวัน",
    department: "IE",
    classYear: 78,
    position: "CEO",
    companyName: "Learn Corporation Co,Ltd",
    industries: ["tech-and-innovation"],
    mentorYears: [4, 5],
  },
  {
    id: "mentor-123",
    nickname: "พี่ต๋อม",
    fullName: "วิศรุต ศรีโรจนกุล",
    department: "CHEM",
    classYear: 81,
    position: "Deputy CFO",
    companyName: "บริษัท วินเวสต์เม้นท์ จำกัด",
    industries: ["financial-and-investment"],
    mentorYears: [4, 5],
  },
  {
    id: "mentor-124",
    nickname: "พี่หนึ่ง",
    fullName: "ถิรนันท์ อรุณวัฒนกูล",
    department: "IE",
    classYear: 88,
    position: "COO",
    companyName: "MONIX",
    industries: ["tech-and-innovation", "financial-and-investment"],
    mentorYears: [4, 5],
  },
  {
    id: "mentor-125",
    nickname: "พี่กบ",
    fullName: "จรัล งามวิโรจน์เจริญ",
    department: "EE",
    classYear: 74,
    position: "Director (CEO Office)",
    companyName: "Carabao Group",
    industries: ["tech-and-innovation", "food-and-beverage"],
    mentorYears: [4],
  },
  {
    id: "mentor-126",
    nickname: "พี่จิ๊ก",
    fullName: "ชยงค์ บริสุทธิ์สวัสดิ์",
    department: "PETRO",
    classYear: 69,
    position: "รองกรรมการผู้จัดการใหญ่",
    companyName: "ปตท สำรวจและผลิตปิโตรเลียม",
    industries: ["engineering"],
    mentorYears: [5],
  },
  {
    id: "mentor-127",
    nickname: "พี่นก",
    fullName: "มณีรัตน์ อนุโลมสมบัติ",
    department: "IE",
    classYear: 80,
    position: "CEO",
    companyName: "Sea Thailand",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [5],
  },

  // ---------------------------------------------------------------------------
  // mentor-128..136 — first-time ChAMP 9 mentors, added after the Champ9
  // Airtable table gained new rows. Photos come from that table's
  // Profile_Picture attachments; run `node scripts/download-mentor-photos.mjs`
  // to pull them into public/mentors/. That script is always scoped to just the
  // mentors whose photo is still missing, and it skips any file already on
  // disk, so it will not overwrite the hand-picked images for mentor-01..71.
  // Every one of them also has a company Logo attachment in Airtable that is
  // not wired up here — see `companyLogoUrl` in the notes at the top.
  // ---------------------------------------------------------------------------
  {
    id: "mentor-128",
    mentorPictureUrl: "/mentors/mentor-128.png",
    nickname: "พี่ไมค์",
    fullName: "กานต์ โอภาสจำรัสกิจ",
    department: "EE",
    classYear: 80,
    position: "Head of Security IC Product Line",
    companyName: "Silicon Craft Technology PLC",
    industries: ["tech-and-innovation", "manufacturing"],
    mentorYears: [9],
  },
  {
    id: "mentor-129",
    mentorPictureUrl: "/mentors/mentor-129.png",
    nickname: "พี่บอย",
    fullName: "ภัทราวุธ ซื่อสัตยาศิลป์",
    department: "CP",
    classYear: 84,
    position: "CTO",
    companyName: "LINE MAN Wongnai",
    industries: ["tech-and-innovation", "food-and-beverage"],
    mentorYears: [9],
  },
  {
    id: "mentor-130",
    mentorPictureUrl: "/mentors/mentor-130.jpg",
    nickname: "พี่นัน",
    fullName: "นันท์ชนก เมฆมาสิน",
    department: "CHEM",
    classYear: 87,
    position: "Associate Partner",
    companyName: "Bain & Company",
    industries: ["commercial-and-marketing"],
    mentorYears: [9],
  },
  {
    id: "mentor-131",
    mentorPictureUrl: "/mentors/mentor-131.jpg",
    nickname: "พี่แจ๊ค",
    fullName: "รตนพล บุบผาชาติ",
    department: "CP",
    classYear: 84,
    position: "Managing Director",
    companyName: "Playtorium Solutions Public Company Limited",
    industries: ["tech-and-innovation"],
    mentorYears: [9],
  },
  {
    id: "mentor-132",
    mentorPictureUrl: "/mentors/mentor-132.jpg",
    nickname: "พี่นัท",
    fullName: "วนัชพร ณ เชียงใหม่",
    department: "CHEM",
    classYear: 87,
    position: "Commercial Director",
    companyName: "Bluebik",
    industries: ["tech-and-innovation", "commercial-and-marketing"],
    mentorYears: [9],
  },
  {
    id: "mentor-133",
    mentorPictureUrl: "/mentors/mentor-133.jpg",
    nickname: "พี่ป๋วย",
    fullName: "สาโรช คุณวุฒิพร",
    department: "IE",
    classYear: 94,
    position: "Global Supply Chain Transformation Lead",
    companyName: "Mars Petcare",
    industries: ["manufacturing", "food-and-beverage"],
    mentorYears: [9],
  },
  {
    id: "mentor-134",
    mentorPictureUrl: "/mentors/mentor-134.png",
    nickname: "พี่เชาว์",
    fullName: "เชาว์เลิศ ลีลาศวัฒนกุล",
    department: "ME",
    classYear: 85,
    position: "Deputy Managing Director",
    companyName: "Lucky Flame",
    industries: ["manufacturing"],
    mentorYears: [9],
  },
  {
    id: "mentor-135",
    mentorPictureUrl: "/mentors/mentor-135.jpg",
    nickname: "พี่กิด",
    fullName: "กฤษณ์ พรพิไลลักษณ์",
    department: "AE",
    classYear: 95,
    position: "CEO",
    companyName: "SolarPPM Company Limited",
    industries: ["engineering"],
    mentorYears: [9],
  },
  {
    id: "mentor-136",
    mentorPictureUrl: "/mentors/mentor-136.jpg",
    nickname: "พี่มด",
    fullName: "อิทธิพันธ์ เจียกเจิม",
    department: "CIVIL",
    classYear: 79,
    position: "CFO",
    companyName: "CLICX Bank PCL",
    industries: ["financial-and-investment"],
    mentorYears: [9],
  },
];

/** Highest program year a mentor served in: `[3, 4, 5, 8, 9]` -> `9`. */
export function latestMentorYear(mentor: Mentor): number {
  return mentor.mentorYears.reduce(
    (latest, year) => (year > latest ? year : latest),
    0,
  );
}

/**
 * Most recent mentors first — everyone still mentoring in ChAMP 9, then those
 * whose last year was 8, and so on down to ChAMP 1. Mentors who share a latest
 * year fall back to `id` ascending, compared numerically so that mentor-99
 * sorts before mentor-100 rather than after it.
 */
export function sortMentorsByLatestYear(allMentors: Mentor[]): Mentor[] {
  return [...allMentors].sort((a, b) => {
    const byLatestYear = latestMentorYear(b) - latestMentorYear(a);

    return byLatestYear !== 0
      ? byLatestYear
      : a.id.localeCompare(b.id, "en", { numeric: true });
  });
}

export function filterMentors(
  allMentors: Mentor[],
  {
    industries,
    programYear,
  }: {
    /** Empty means "no industry filter applied". */
    industries: MentorIndustry[];
    /** `null` shows every mentor, whichever year they served. */
    programYear: number | null;
  },
): Mentor[] {
  return allMentors.filter((mentor) => {
    const matchesYear =
      programYear === null || mentor.mentorYears.includes(programYear);
    const matchesIndustry =
      industries.length === 0 ||
      industries.some((industry) => mentor.industries.includes(industry));

    return matchesYear && matchesIndustry;
  });
}
